# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        admin_config:
            toolbar: full
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                    
        comment_config:
            toolbar: "comment_tools"


    toolbars:
        configs:
            comment_tools: [ "@document", "/", "@colors" ]
        items:
            document: [ "Bold", "-", "Italic" ]
            colors: [ "TextColor", "BGColor" ]


twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
